image: node:18

pipelines:
  default:
    - step:
        script:
          - npm install
          - npm run lint:js
          - npm run test:amplience-core
          - npm run test:cms
          - npm run compile:scss
          - node node_modules/.bin/dwupload --hostname ${HOSTNAME} --username ${USERNAME} --password "${PASSWORD}" --cartridge cartridges/bm_accelerator
          - node node_modules/.bin/dwupload --hostname ${HOSTNAME} --username ${USERNAME} --password "${PASSWORD}" --cartridge cartridges/app_custom_cms
