## cartridge.properties for cartridge bm_accelerator
demandware.cartridges.bm_accelerator.id=bm_accelerator
demandware.cartridges.bm_accelerator.multipleLanguageStorefront=true
demandware.cartridges.bm_accelerator.version=1.0.0
