'use strict';

/**
 * Shopify Standard Product Taxonomy — L1 through L3.
 * Source: Shopify product taxonomy (public standard).
 * Format: { id, name, parentId } — id/parentId are slugs.
 */
var TAXONOMY = [
  // ─── Animals & Pet Supplies ───────────────────────────────────────────
  { id: 'animals-pet-supplies',                    name: 'Animals & Pet Supplies',               parentId: '' },
  { id: 'live-animals',                            name: 'Live Animals',                         parentId: 'animals-pet-supplies' },
  { id: 'pet-supplies',                            name: 'Pet Supplies',                         parentId: 'animals-pet-supplies' },
  { id: 'bird-supplies',                           name: 'Bird Supplies',                        parentId: 'pet-supplies' },
  { id: 'cat-supplies',                            name: 'Cat Supplies',                         parentId: 'pet-supplies' },
  { id: 'dog-supplies',                            name: 'Dog Supplies',                         parentId: 'pet-supplies' },
  { id: 'fish-aquatic-pet-supplies',               name: 'Fish & Aquatic Pet Supplies',          parentId: 'pet-supplies' },
  { id: 'reptile-supplies',                        name: 'Reptile Supplies',                     parentId: 'pet-supplies' },
  { id: 'small-animal-supplies',                   name: 'Small Animal Supplies',                parentId: 'pet-supplies' },

  // ─── Apparel & Accessories ────────────────────────────────────────────
  { id: 'apparel-accessories',                     name: 'Apparel & Accessories',                parentId: '' },
  { id: 'clothing',                                name: 'Clothing',                             parentId: 'apparel-accessories' },
  { id: 'costumes-accessories',                    name: 'Costumes & Accessories',               parentId: 'apparel-accessories' },
  { id: 'handbag-wallet-accessories',              name: 'Handbag & Wallet Accessories',         parentId: 'apparel-accessories' },
  { id: 'handbags-wallets-cases',                  name: 'Handbags, Wallets & Cases',            parentId: 'apparel-accessories' },
  { id: 'jewelry',                                 name: 'Jewelry',                              parentId: 'apparel-accessories' },
  { id: 'shoes',                                   name: 'Shoes',                                parentId: 'apparel-accessories' },
  { id: 'clothing-accessories',                    name: 'Clothing Accessories',                 parentId: 'apparel-accessories' },
  { id: 'activewear',                              name: 'Activewear',                           parentId: 'clothing' },
  { id: 'baby-toddler-clothing',                   name: 'Baby & Toddler Clothing',              parentId: 'clothing' },
  { id: 'dresses',                                 name: 'Dresses',                              parentId: 'clothing' },
  { id: 'mens-clothing',                           name: "Men's Clothing",                       parentId: 'clothing' },
  { id: 'outerwear',                               name: 'Outerwear',                            parentId: 'clothing' },
  { id: 'sleepwear-loungewear',                    name: 'Sleepwear & Loungewear',               parentId: 'clothing' },
  { id: 'suits',                                   name: 'Suits',                                parentId: 'clothing' },
  { id: 'swimwear',                                name: 'Swimwear',                             parentId: 'clothing' },
  { id: 'tops',                                    name: 'Tops',                                 parentId: 'clothing' },
  { id: 'uniforms',                                name: 'Uniforms',                             parentId: 'clothing' },
  { id: 'wedding-bridal-party-dresses',            name: 'Wedding & Bridal Party Dresses',       parentId: 'clothing' },
  { id: 'womens-clothing',                         name: "Women's Clothing",                     parentId: 'clothing' },
  { id: 'bracelets',                               name: 'Bracelets',                            parentId: 'jewelry' },
  { id: 'earrings',                                name: 'Earrings',                             parentId: 'jewelry' },
  { id: 'necklaces',                               name: 'Necklaces',                            parentId: 'jewelry' },
  { id: 'rings',                                   name: 'Rings',                                parentId: 'jewelry' },
  { id: 'watches',                                 name: 'Watches',                              parentId: 'jewelry' },
  { id: 'boots',                                   name: 'Boots',                                parentId: 'shoes' },
  { id: 'flats',                                   name: 'Flats',                                parentId: 'shoes' },
  { id: 'heels',                                   name: 'Heels',                                parentId: 'shoes' },
  { id: 'sandals',                                 name: 'Sandals',                              parentId: 'shoes' },
  { id: 'sneakers-athletic-shoes',                 name: 'Sneakers & Athletic Shoes',            parentId: 'shoes' },
  { id: 'hats-caps',                               name: 'Hats & Caps',                         parentId: 'clothing-accessories' },
  { id: 'scarves-wraps',                           name: 'Scarves & Wraps',                      parentId: 'clothing-accessories' },
  { id: 'sunglasses',                              name: 'Sunglasses',                           parentId: 'clothing-accessories' },
  { id: 'belts',                                   name: 'Belts',                                parentId: 'clothing-accessories' },
  { id: 'gloves-mittens',                          name: 'Gloves & Mittens',                     parentId: 'clothing-accessories' },

  // ─── Arts & Entertainment ─────────────────────────────────────────────
  { id: 'arts-entertainment',                      name: 'Arts & Entertainment',                 parentId: '' },
  { id: 'hobbies-creative-arts',                   name: 'Hobbies & Creative Arts',              parentId: 'arts-entertainment' },
  { id: 'party-celebration',                       name: 'Party & Celebration',                  parentId: 'arts-entertainment' },
  { id: 'art-craft-supplies',                      name: 'Art & Craft Supplies',                 parentId: 'hobbies-creative-arts' },
  { id: 'musical-instruments',                     name: 'Musical Instruments',                  parentId: 'hobbies-creative-arts' },
  { id: 'collectibles',                            name: 'Collectibles',                         parentId: 'hobbies-creative-arts' },
  { id: 'event-entertainment-supplies',            name: 'Event & Entertainment Supplies',       parentId: 'party-celebration' },
  { id: 'gift-giving',                             name: 'Gift Giving',                          parentId: 'party-celebration' },

  // ─── Baby & Toddler ───────────────────────────────────────────────────
  { id: 'baby-toddler',                            name: 'Baby & Toddler',                       parentId: '' },
  { id: 'baby-toddler-clothing-l2',               name: 'Baby & Toddler Clothing',              parentId: 'baby-toddler' },
  { id: 'baby-toddler-diapering',                  name: 'Diapering',                            parentId: 'baby-toddler' },
  { id: 'baby-toddler-feeding',                    name: 'Baby & Toddler Feeding',               parentId: 'baby-toddler' },
  { id: 'baby-toddler-furniture',                  name: 'Baby & Toddler Furniture',             parentId: 'baby-toddler' },
  { id: 'baby-toddler-toys',                       name: 'Baby & Toddler Toys',                  parentId: 'baby-toddler' },
  { id: 'strollers',                               name: 'Strollers',                            parentId: 'baby-toddler' },

  // ─── Business & Industrial ────────────────────────────────────────────
  { id: 'business-industrial',                     name: 'Business & Industrial',                parentId: '' },
  { id: 'agriculture',                             name: 'Agriculture',                          parentId: 'business-industrial' },
  { id: 'construction',                            name: 'Construction',                         parentId: 'business-industrial' },
  { id: 'food-service',                            name: 'Food Service',                         parentId: 'business-industrial' },
  { id: 'industrial-storage',                      name: 'Industrial Storage',                   parentId: 'business-industrial' },
  { id: 'janitorial',                              name: 'Janitorial',                           parentId: 'business-industrial' },
  { id: 'manufacturing',                           name: 'Manufacturing',                        parentId: 'business-industrial' },
  { id: 'medical',                                 name: 'Medical',                              parentId: 'business-industrial' },

  // ─── Cameras & Optics ─────────────────────────────────────────────────
  { id: 'cameras-optics',                          name: 'Cameras & Optics',                     parentId: '' },
  { id: 'camera-accessories',                      name: 'Camera Accessories',                   parentId: 'cameras-optics' },
  { id: 'cameras',                                 name: 'Cameras',                              parentId: 'cameras-optics' },
  { id: 'optics',                                  name: 'Optics',                               parentId: 'cameras-optics' },
  { id: 'digital-cameras',                         name: 'Digital Cameras',                      parentId: 'cameras' },
  { id: 'film-cameras',                            name: 'Film Cameras',                         parentId: 'cameras' },
  { id: 'security-cameras',                        name: 'Security Cameras',                     parentId: 'cameras' },
  { id: 'binoculars',                              name: 'Binoculars',                           parentId: 'optics' },
  { id: 'telescopes',                              name: 'Telescopes',                           parentId: 'optics' },

  // ─── Electronics ──────────────────────────────────────────────────────
  { id: 'electronics',                             name: 'Electronics',                          parentId: '' },
  { id: 'audio',                                   name: 'Audio',                                parentId: 'electronics' },
  { id: 'circuit-board-components',               name: 'Circuit Boards & Components',          parentId: 'electronics' },
  { id: 'communications',                          name: 'Communications',                       parentId: 'electronics' },
  { id: 'computers',                               name: 'Computers',                            parentId: 'electronics' },
  { id: 'electronics-accessories',                 name: 'Electronics Accessories',              parentId: 'electronics' },
  { id: 'gps-navigation',                          name: 'GPS & Navigation',                     parentId: 'electronics' },
  { id: 'marine-electronics',                      name: 'Marine Electronics',                   parentId: 'electronics' },
  { id: 'networking',                              name: 'Networking',                           parentId: 'electronics' },
  { id: 'print-scan-fax',                          name: 'Print, Scan & Fax',                    parentId: 'electronics' },
  { id: 'televisions',                             name: 'Televisions',                          parentId: 'electronics' },
  { id: 'video',                                   name: 'Video',                                parentId: 'electronics' },
  { id: 'video-game-consoles',                     name: 'Video Game Consoles',                  parentId: 'electronics' },
  { id: 'headphones',                              name: 'Headphones',                           parentId: 'audio' },
  { id: 'speakers',                                name: 'Speakers',                             parentId: 'audio' },
  { id: 'desktops',                                name: 'Desktops',                             parentId: 'computers' },
  { id: 'laptops',                                 name: 'Laptops',                              parentId: 'computers' },
  { id: 'tablets',                                 name: 'Tablets',                              parentId: 'computers' },
  { id: 'mobile-phones',                           name: 'Mobile Phones',                        parentId: 'communications' },
  { id: 'smart-watches',                           name: 'Smart Watches',                        parentId: 'electronics-accessories' },

  // ─── Food, Beverages & Tobacco ────────────────────────────────────────
  { id: 'food-beverages-tobacco',                  name: 'Food, Beverages & Tobacco',            parentId: '' },
  { id: 'beverages',                               name: 'Beverages',                            parentId: 'food-beverages-tobacco' },
  { id: 'food-items',                              name: 'Food Items',                           parentId: 'food-beverages-tobacco' },
  { id: 'tobacco-products',                        name: 'Tobacco Products',                     parentId: 'food-beverages-tobacco' },
  { id: 'alcoholic-beverages',                     name: 'Alcoholic Beverages',                  parentId: 'beverages' },
  { id: 'coffee-tea',                              name: 'Coffee & Tea',                         parentId: 'beverages' },
  { id: 'juices',                                  name: 'Juices',                               parentId: 'beverages' },
  { id: 'soft-drinks',                             name: 'Soft Drinks',                         parentId: 'beverages' },
  { id: 'water',                                   name: 'Water',                                parentId: 'beverages' },
  { id: 'baked-goods',                             name: 'Baked Goods',                          parentId: 'food-items' },
  { id: 'candy-chocolate',                         name: 'Candy & Chocolate',                    parentId: 'food-items' },
  { id: 'condiments-sauces',                       name: 'Condiments & Sauces',                  parentId: 'food-items' },
  { id: 'dairy-eggs',                              name: 'Dairy & Eggs',                         parentId: 'food-items' },
  { id: 'grains-pasta',                            name: 'Grains & Pasta',                       parentId: 'food-items' },
  { id: 'meat-seafood',                            name: 'Meat & Seafood',                       parentId: 'food-items' },
  { id: 'snack-foods',                             name: 'Snack Foods',                          parentId: 'food-items' },

  // ─── Furniture ────────────────────────────────────────────────────────
  { id: 'furniture',                               name: 'Furniture',                            parentId: '' },
  { id: 'bedroom-furniture',                       name: 'Bedroom Furniture',                    parentId: 'furniture' },
  { id: 'living-room-furniture',                   name: 'Living Room Furniture',                parentId: 'furniture' },
  { id: 'office-furniture',                        name: 'Office Furniture',                     parentId: 'furniture' },
  { id: 'outdoor-furniture',                       name: 'Outdoor Furniture',                    parentId: 'furniture' },
  { id: 'storage-organization',                    name: 'Storage & Organization',               parentId: 'furniture' },
  { id: 'beds-headboards',                         name: 'Beds & Headboards',                    parentId: 'bedroom-furniture' },
  { id: 'dressers-chests',                         name: 'Dressers & Chests',                    parentId: 'bedroom-furniture' },
  { id: 'nightstands',                             name: 'Nightstands',                          parentId: 'bedroom-furniture' },
  { id: 'sofas-sectionals',                        name: 'Sofas & Sectionals',                   parentId: 'living-room-furniture' },
  { id: 'tv-stands-entertainment-centers',        name: 'TV Stands & Entertainment Centers',    parentId: 'living-room-furniture' },
  { id: 'chairs',                                  name: 'Chairs',                               parentId: 'living-room-furniture' },
  { id: 'desks',                                   name: 'Desks',                                parentId: 'office-furniture' },

  // ─── Hardware ─────────────────────────────────────────────────────────
  { id: 'hardware',                                name: 'Hardware',                             parentId: '' },
  { id: 'building-materials',                      name: 'Building Materials',                   parentId: 'hardware' },
  { id: 'electrical',                              name: 'Electrical',                           parentId: 'hardware' },
  { id: 'fasteners',                               name: 'Fasteners',                            parentId: 'hardware' },
  { id: 'hand-tools',                              name: 'Hand Tools',                           parentId: 'hardware' },
  { id: 'heating-venting-cooling',                 name: 'Heating, Venting & Cooling',           parentId: 'hardware' },
  { id: 'locks-safes',                             name: 'Locks & Safes',                        parentId: 'hardware' },
  { id: 'plumbing',                                name: 'Plumbing',                             parentId: 'hardware' },
  { id: 'power-tools',                             name: 'Power Tools',                          parentId: 'hardware' },
  { id: 'tool-accessories',                        name: 'Tool Accessories',                     parentId: 'hardware' },

  // ─── Health & Beauty ──────────────────────────────────────────────────
  { id: 'health-beauty',                           name: 'Health & Beauty',                      parentId: '' },
  { id: 'health-care',                             name: 'Health Care',                          parentId: 'health-beauty' },
  { id: 'personal-care',                           name: 'Personal Care',                        parentId: 'health-beauty' },
  { id: 'vitamins-supplements',                    name: 'Vitamins & Supplements',               parentId: 'health-beauty' },
  { id: 'bath-body',                               name: 'Bath & Body',                          parentId: 'personal-care' },
  { id: 'fragrances',                              name: 'Fragrances',                           parentId: 'personal-care' },
  { id: 'hair-care',                               name: 'Hair Care',                            parentId: 'personal-care' },
  { id: 'make-up',                                 name: 'Make-Up',                              parentId: 'personal-care' },
  { id: 'nail-care',                               name: 'Nail Care',                            parentId: 'personal-care' },
  { id: 'oral-care',                               name: 'Oral Care',                            parentId: 'personal-care' },
  { id: 'shaving-grooming',                        name: 'Shaving & Grooming',                   parentId: 'personal-care' },
  { id: 'skin-care',                               name: 'Skin Care',                            parentId: 'personal-care' },
  { id: 'first-aid',                               name: 'First Aid',                            parentId: 'health-care' },
  { id: 'medical-devices',                         name: 'Medical Devices',                      parentId: 'health-care' },

  // ─── Home & Garden ────────────────────────────────────────────────────
  { id: 'home-garden',                             name: 'Home & Garden',                        parentId: '' },
  { id: 'bed-bath',                                name: 'Bed & Bath',                           parentId: 'home-garden' },
  { id: 'decor',                                   name: 'Decor',                                parentId: 'home-garden' },
  { id: 'emergency-preparedness',                  name: 'Emergency Preparedness',               parentId: 'home-garden' },
  { id: 'fireplace-wood-stove-accessories',        name: 'Fireplace & Wood Stove Accessories',   parentId: 'home-garden' },
  { id: 'garden-outdoor',                          name: 'Garden & Outdoor',                     parentId: 'home-garden' },
  { id: 'household-appliances',                    name: 'Household Appliances',                 parentId: 'home-garden' },
  { id: 'household-supplies',                      name: 'Household Supplies',                   parentId: 'home-garden' },
  { id: 'kitchen-dining',                          name: 'Kitchen & Dining',                     parentId: 'home-garden' },
  { id: 'lawn-garden',                             name: 'Lawn & Garden',                        parentId: 'home-garden' },
  { id: 'lighting',                                name: 'Lighting',                             parentId: 'home-garden' },
  { id: 'pillows-cushions',                        name: 'Pillows & Cushions',                   parentId: 'bed-bath' },
  { id: 'rugs',                                    name: 'Rugs',                                 parentId: 'decor' },
  { id: 'wall-art',                                name: 'Wall Art',                             parentId: 'decor' },
  { id: 'candles',                                 name: 'Candles',                              parentId: 'decor' },
  { id: 'cookware',                                name: 'Cookware',                             parentId: 'kitchen-dining' },
  { id: 'bakeware',                                name: 'Bakeware',                             parentId: 'kitchen-dining' },
  { id: 'cutlery',                                 name: 'Cutlery',                              parentId: 'kitchen-dining' },
  { id: 'kitchen-tools-gadgets',                   name: 'Kitchen Tools & Gadgets',              parentId: 'kitchen-dining' },
  { id: 'small-appliances',                        name: 'Small Appliances',                     parentId: 'household-appliances' },
  { id: 'large-appliances',                        name: 'Large Appliances',                     parentId: 'household-appliances' },
  { id: 'garden-tools',                            name: 'Garden Tools',                         parentId: 'lawn-garden' },
  { id: 'outdoor-power-equipment',                 name: 'Outdoor Power Equipment',              parentId: 'lawn-garden' },
  { id: 'plants-seeds',                            name: 'Plants & Seeds',                       parentId: 'lawn-garden' },
  { id: 'soil-fertilizers',                        name: 'Soil & Fertilizers',                   parentId: 'lawn-garden' },

  // ─── Luggage & Bags ───────────────────────────────────────────────────
  { id: 'luggage-bags',                            name: 'Luggage & Bags',                       parentId: '' },
  { id: 'backpacks',                               name: 'Backpacks',                            parentId: 'luggage-bags' },
  { id: 'briefcases',                              name: 'Briefcases',                           parentId: 'luggage-bags' },
  { id: 'luggage',                                 name: 'Luggage',                              parentId: 'luggage-bags' },
  { id: 'messenger-shoulder-bags',                 name: 'Messenger & Shoulder Bags',            parentId: 'luggage-bags' },
  { id: 'travel-accessories',                      name: 'Travel Accessories',                   parentId: 'luggage-bags' },

  // ─── Media ────────────────────────────────────────────────────────────
  { id: 'media',                                   name: 'Media',                                parentId: '' },
  { id: 'books',                                   name: 'Books',                                parentId: 'media' },
  { id: 'magazines-newspapers',                    name: 'Magazines & Newspapers',               parentId: 'media' },
  { id: 'movies',                                  name: 'Movies',                               parentId: 'media' },
  { id: 'music',                                   name: 'Music',                                parentId: 'media' },
  { id: 'product-manuals-guides',                  name: 'Product Manuals & Guides',             parentId: 'media' },
  { id: 'sheet-music',                             name: 'Sheet Music',                          parentId: 'media' },
  { id: 'video-games',                             name: 'Video Games',                          parentId: 'media' },

  // ─── Office Supplies ──────────────────────────────────────────────────
  { id: 'office-supplies',                         name: 'Office Supplies',                      parentId: '' },
  { id: 'desk-accessories',                        name: 'Desk Accessories & Workspace Organizers', parentId: 'office-supplies' },
  { id: 'filing-binding',                          name: 'Filing & Binding',                     parentId: 'office-supplies' },
  { id: 'mailing-shipping',                        name: 'Mailing & Shipping',                   parentId: 'office-supplies' },
  { id: 'presentation-supplies',                   name: 'Presentation Supplies',                parentId: 'office-supplies' },
  { id: 'writing-instruments',                     name: 'Writing & Drawing Instruments',        parentId: 'office-supplies' },
  { id: 'paper',                                   name: 'Paper',                                parentId: 'office-supplies' },

  // ─── Sporting Goods ───────────────────────────────────────────────────
  { id: 'sporting-goods',                          name: 'Sporting Goods',                       parentId: '' },
  { id: 'athletics',                               name: 'Athletics',                            parentId: 'sporting-goods' },
  { id: 'cycling',                                 name: 'Cycling',                              parentId: 'sporting-goods' },
  { id: 'exercise-fitness',                        name: 'Exercise & Fitness',                   parentId: 'sporting-goods' },
  { id: 'golf',                                    name: 'Golf',                                 parentId: 'sporting-goods' },
  { id: 'outdoor-recreation',                      name: 'Outdoor Recreation',                   parentId: 'sporting-goods' },
  { id: 'racquet-sports',                          name: 'Racquet Sports',                       parentId: 'sporting-goods' },
  { id: 'snow-sports',                             name: 'Snow Sports',                          parentId: 'sporting-goods' },
  { id: 'team-sports',                             name: 'Team Sports',                          parentId: 'sporting-goods' },
  { id: 'water-sports',                            name: 'Water Sports',                         parentId: 'sporting-goods' },
  { id: 'basketball',                              name: 'Basketball',                           parentId: 'team-sports' },
  { id: 'football',                                name: 'Football',                             parentId: 'team-sports' },
  { id: 'soccer',                                  name: 'Soccer',                               parentId: 'team-sports' },
  { id: 'baseball-softball',                       name: 'Baseball & Softball',                  parentId: 'team-sports' },
  { id: 'camping-hiking',                          name: 'Camping & Hiking',                     parentId: 'outdoor-recreation' },
  { id: 'fishing',                                 name: 'Fishing',                              parentId: 'outdoor-recreation' },
  { id: 'hunting',                                 name: 'Hunting',                              parentId: 'outdoor-recreation' },
  { id: 'tennis',                                  name: 'Tennis',                               parentId: 'racquet-sports' },
  { id: 'badminton',                               name: 'Badminton',                            parentId: 'racquet-sports' },

  // ─── Toys & Games ─────────────────────────────────────────────────────
  { id: 'toys-games',                              name: 'Toys & Games',                         parentId: '' },
  { id: 'board-games-puzzles',                     name: 'Board Games & Puzzles',                parentId: 'toys-games' },
  { id: 'building-construction-toys',              name: 'Building & Construction Toys',         parentId: 'toys-games' },
  { id: 'dolls-accessories',                       name: 'Dolls & Accessories',                  parentId: 'toys-games' },
  { id: 'games',                                   name: 'Games',                                parentId: 'toys-games' },
  { id: 'outdoor-toys-activity',                   name: 'Outdoor Toys & Activity',              parentId: 'toys-games' },
  { id: 'stuffed-toys',                            name: 'Stuffed Toys',                         parentId: 'toys-games' },
  { id: 'toy-figures-playsets',                    name: 'Toy Figures & Playsets',               parentId: 'toys-games' },
  { id: 'vehicles-ride-ons',                       name: 'Vehicles & Ride-Ons',                  parentId: 'toys-games' },

  // ─── Vehicles & Parts ─────────────────────────────────────────────────
  { id: 'vehicles-parts',                          name: 'Vehicles & Parts',                     parentId: '' },
  { id: 'motor-vehicles',                          name: 'Motor Vehicles',                       parentId: 'vehicles-parts' },
  { id: 'vehicle-parts-accessories',               name: 'Vehicle Parts & Accessories',          parentId: 'vehicles-parts' },
  { id: 'watercraft',                              name: 'Watercraft',                           parentId: 'vehicles-parts' },
  { id: 'cars',                                    name: 'Cars',                                 parentId: 'motor-vehicles' },
  { id: 'motorcycles',                             name: 'Motorcycles',                          parentId: 'motor-vehicles' },
  { id: 'trucks',                                  name: 'Trucks',                               parentId: 'motor-vehicles' },
  { id: 'auto-parts',                              name: 'Auto Parts',                           parentId: 'vehicle-parts-accessories' },
  { id: 'auto-tools-equipment',                    name: 'Auto Tools & Equipment',               parentId: 'vehicle-parts-accessories' },
  { id: 'car-care',                                name: 'Car Care',                             parentId: 'vehicle-parts-accessories' }
];

module.exports = { TAXONOMY: TAXONOMY };
